name: CI - Supabase Migrations (dry-run)
on: [pull_request]
jobs:
  supabase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm i
      - run: echo "no supabase cli install needed for dry run"
      - run: test -d supabase/migrations && echo "migrations folder ok" || echo "no migrations"

