name: CI - Supabase Migrations (dry-run)
on: [pull_request]
jobs:
  supabase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: echo "no supabase cli install needed for dry run"
      - run: test -d supabase/migrations && echo "migrations folder ok" || echo "no migrations"

